version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WEBAPP_EXTERNAL_PORT}:${WEBAPP_INTERNAL_PORT}"
    environment:
      - NODE_ENV=development
    container_name: ${PROJECT_NAME}
    networks:
      - project_network

networks:
  project_network:
    driver: bridge